# ctbot-container
# Copyright (C) 2021 Timo Sandmann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

ARG base_version=2.28
FROM ctsim:$base_version

USER root
RUN apt-get install -y ant

USER developer
ENV HOME /home/developer
COPY container_data/entry_ctsim-dev.sh /opt/entry.sh

ARG version=master
WORKDIR /data
ENTRYPOINT /opt/entry.sh $version

