FROM debian:buster-slim
RUN apt-get -y update
RUN mkdir -p /usr/share/man/man1
RUN apt-get install -y --no-install-recommends locales bash git wget ssh apt-transport-https ca-certificates dirmngr gnupg software-properties-common && apt-get -y update
RUN sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && locale-gen

RUN apt-get install -y --no-install-recommends mesa-utils libgl1-mesa-glx libgl1-mesa-dri
RUN wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - && add-apt-repository https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ && apt-get update
RUN apt-get install -y adoptopenjdk-8-hotspot fontconfig ant

RUN useradd -m -u 1000 -G dialout,sudo -s /bin/bash developer && echo "developer:ct-bot" | chpasswd

USER developer
ENV HOME /home/developer
COPY entry_ctsim-dev.sh /opt/entry.sh

ARG version=master
WORKDIR /data
ENTRYPOINT /opt/entry.sh $version

